In [42]:
import pandas as pd
import scipy.stats
import pickle
import numpy as np

# Localizer

In [2]:
df = pd.read_csv("/Volumes/clmnlab/GA/MVPA/LSS_pb02_MO_short_duration/roi_mvpa/20200313/localizer/20200313_localizer_dec-acc.csv")
df.tail()

,Unnamed: 0,subj,roi_name,Mapping,Mean Accuracy,Stage
1075,1075,GA44,n200_c6_R_CerebellumVIIIb,Unpracticed,0.277778,Late
1076,1076,GA44,n200_c7_L_Thalamus,Practiced,0.302083,Early
1077,1077,GA44,n200_c7_L_Thalamus,Practiced,0.270833,Late
1078,1078,GA44,n200_c7_L_Thalamus,Unpracticed,0.288194,Early
1079,1079,GA44,n200_c7_L_Thalamus,Unpracticed,0.236111,Late

In [8]:
roi_names = sorted(set(df['roi_name']))

lines = []

for roi_name in roi_names:
    for stage in ['Early', 'Late']:
        for mapping in ['Practiced', 'Unpracticed']:
            accuracies = df[(df['Mapping'] == mapping) & (df['Stage'] == stage) & (df['roi_name'] == roi_name)]['Mean Accuracy']
            res = scipy.stats.ttest_1samp(a=accuracies, popmean=0.25)
            lines.append((roi_name, stage, mapping, res.statistic, res.pvalue))

In [10]:
result_df = pd.DataFrame(lines, columns=['cluster_name', 'stage', 'mapping', 't-value', 'p-value'])
result_df

                 cluster_name  stage      mapping    t-value       p-value
0              n200_c1-1_L_M1  Early    Practiced   7.921364  9.780284e-09
1              n200_c1-1_L_M1  Early  Unpracticed   7.779672  1.403512e-08
2              n200_c1-1_L_M1   Late    Practiced   7.701820  1.713444e-08
3              n200_c1-1_L_M1   Late  Unpracticed   9.473547  2.218507e-10
4              n200_c1-2_L_S1  Early    Practiced  10.376136  2.837046e-11
5              n200_c1-2_L_S1  Early  Unpracticed  10.957528  7.968436e-12
6              n200_c1-2_L_S1   Late    Practiced   9.493164  2.119141e-10
7              n200_c1-2_L_S1   Late  Unpracticed   9.059574  5.904175e-10
8       n200_c1_L_Postcentral  Early    Practiced   8.703611  1.394858e-09
9       n200_c1_L_Postcentral  Early  Unpracticed  10.389692  2.752945e-11
10      n200_c1_L_Postcentral   Late    Practiced   9.662906  1.428467e-10
11      n200_c1_L_Postcentral   Late  Unpracticed   9.955028  7.309749e-11
12   n200_c2_R_CerebellumIV-V  Early    Practiced   3.806147  6.754291e-04
13   n200_c2_R_CerebellumIV-V  Early  Unpracticed   8.253749  4.233879e-09
14   n200_c2_R_CerebellumIV-V   Late    Practiced   4.503414  1.005814e-04
15   n200_c2_R_CerebellumIV-V   Late  Unpracticed   7.617752  2.127210e-08
16      n200_c3_R_Postcentral  Early    Practiced   9.022293  6.455393e-10
17      n200_c3_R_Postcentral  Early  Unpracticed   7.659193  1.911857e-08
18      n200_c3_R_Postcentral   Late    Practiced   8.308319  3.695153e-09
19      n200_c3_R_Postcentral   Late  Unpracticed   8.625183  1.689542e-09
20          n200_c4_L_Putamen  Early    Practiced   6.371906  5.772277e-07
21          n200_c4_L_Putamen  Early  Unpracticed   7.365667  4.090207e-08
22          n200_c4_L_Putamen   Late    Practiced   5.467297  6.927208e-06
23          n200_c4_L_Putamen   Late  Unpracticed   6.102192  1.203819e-06
24              n200_c5_R_SMA  Early    Practiced   5.639728  4.297449e-06
25              n200_c5_R_SMA  Early  Unpracticed   6.125133  1.130606e-06
26              n200_c5_R_SMA   Late    Practiced   5.555440  5.426242e-06
27              n200_c5_R_SMA   Late  Unpracticed   6.628763  2.883679e-07
28  n200_c6_R_CerebellumVIIIb  Early    Practiced   5.129903  1.767790e-05
29  n200_c6_R_CerebellumVIIIb  Early  Unpracticed   4.459657  1.135039e-04
30  n200_c6_R_CerebellumVIIIb   Late    Practiced   3.550146  1.335836e-03
31  n200_c6_R_CerebellumVIIIb   Late  Unpracticed   6.197735  9.272307e-07
32         n200_c7_L_Thalamus  Early    Practiced   4.464133  1.121099e-04
33         n200_c7_L_Thalamus  Early  Unpracticed   4.305746  1.734514e-04
34         n200_c7_L_Thalamus   Late    Practiced   2.981967  5.751988e-03
35         n200_c7_L_Thalamus   Late  Unpracticed   3.626544  1.091262e-03

In [11]:
result_df.to_csv('20200327_MVPA_localizer_statistics.csv')

In [13]:
subj_list = [
    'GA01', 'GA02', 'GA05', 'GA07', 'GA08', 'GA11', 'GA12', 'GA13', 'GA14', 'GA15',
    'GA18', 'GA19', 'GA20', 'GA21', 'GA23', 'GA26', 'GA27', 'GA28', 'GA29', 'GA30',
    'GA31', 'GA32', 'GA33', 'GA34', 'GA35', 'GA36', 'GA37', 'GA38', 'GA42', 'GA44'
]

In [27]:
lines = []

for roi_name in roi_names:
    early_accuracies = [float(df[(df['Stage'] == 'Early') & (df['Mapping'] == 'Practiced') & (df['roi_name'] == roi_name) & (df['subj'] == subj)]['Mean Accuracy']) for subj in subj_list]
    late_accuracies = [float(df[(df['Stage'] == 'Late') & (df['Mapping'] == 'Practiced') & (df['roi_name'] == roi_name) & (df['subj'] == subj)]['Mean Accuracy']) for subj in subj_list]
    res = scipy.stats.ttest_rel(early_accuracies, late_accuracies)
    lines.append((roi_name, res.statistic, res.pvalue))

In [29]:
result_df = pd.DataFrame(lines, columns=['cluster_name', 't-value', 'p-value'])
result_df

                cluster_name   t-value   p-value
0             n200_c1-1_L_M1 -3.958274  0.000448
1             n200_c1-2_L_S1 -4.112568  0.000294
2      n200_c1_L_Postcentral -4.574044  0.000083
3   n200_c2_R_CerebellumIV-V -1.865849  0.072207
4      n200_c3_R_Postcentral -1.926143  0.063940
5          n200_c4_L_Putamen -0.863909  0.394728
6              n200_c5_R_SMA -1.338056  0.191276
7  n200_c6_R_CerebellumVIIIb  0.097040  0.923362
8         n200_c7_L_Thalamus  0.832935  0.411689

In [31]:
result_df.to_csv('20200327_MVPA_localizer_paired_statistics.csv')

In [33]:
result_df['p-value'][2:] * 7

2    0.000579
3    0.505450
4    0.447578
5    2.763093
6    1.338933
7    6.463536
8    2.881825
Name: p-value, dtype: float64

In [35]:
from statsmodels.sandbox.stats.multicomp import multipletests

multipletests(result_df['p-value'][2:], alpha=0.05, method='bonferroni')

(array([ True, False, False, False, False, False, False]),
 array([5.79132555e-04, 5.05449668e-01, 4.47577883e-01, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00]),
 0.007300831979014655,
 0.0071428571428571435)

# Visual

In [40]:
with open('20191203_vis-area_dec-acc.pkl', 'rb') as file:
    results = pickle.load(file=file)

In [43]:
wit_results = results

wit_df = pd.DataFrame(columns=['subj', 'roi_name', 'Mapping', 'Mean Accuracy', 'Stage'])

roi_name = 'yeo_network17_1'

for subj in subj_list[:30]:
    wit_df = wit_df.append({'subj': subj,
                    'roi_name': roi_name,
                    'Mapping': 'Unpracticed',
                    'Mean Accuracy': np.mean(wit_results['pos', 'unpracticed', subj, roi_name]),
                    'Stage': 'Early'}, ignore_index=True)

    wit_df = wit_df.append({'subj': subj,
                    'roi_name': roi_name,
                    'Mapping': 'Unpracticed',
                    'Mean Accuracy': np.mean(wit_results['pos', 'unpracticed', subj.replace('A', 'B'), roi_name]),
                    'Stage': 'Late'}, ignore_index=True)
        
    wit_df = wit_df.append({'subj': subj,
                    'roi_name': roi_name,
                    'Mapping': 'Practiced',
                    'Mean Accuracy': np.mean(wit_results['pos', 'practiced', subj, roi_name]),
                    'Stage': 'Early'}, ignore_index=True)

    wit_df = wit_df.append({'subj': subj,
                    'roi_name': roi_name,
                    'Mapping': 'Practiced',
                    'Mean Accuracy': np.mean(wit_results['pos', 'practiced', subj.replace('A', 'B'), roi_name]),
                    'Stage': 'Late'}, ignore_index=True)
    
wit_df.head()

   subj         roi_name      Mapping  Mean Accuracy  Stage
0  GA01  yeo_network17_1  Unpracticed       0.649306  Early
1  GA01  yeo_network17_1  Unpracticed       0.791667   Late
2  GA01  yeo_network17_1    Practiced       0.819444  Early
3  GA01  yeo_network17_1    Practiced       0.559028   Late
4  GA02  yeo_network17_1  Unpracticed       0.802083  Early

In [50]:
wit_df.tail()

     subj         roi_name      Mapping  Mean Accuracy  Stage
115  GA42  yeo_network17_1    Practiced       0.270833   Late
116  GA44  yeo_network17_1  Unpracticed       0.850694  Early
117  GA44  yeo_network17_1  Unpracticed       0.687500   Late
118  GA44  yeo_network17_1    Practiced       0.604167  Early
119  GA44  yeo_network17_1    Practiced       0.927083   Late

In [44]:
wit_df.to_csv('20191203_yeo-network17-1_dec-acc.csv')

In [55]:
lines = []

for stage in ['Early', 'Late']:
    for mapping in ['Practiced', 'Unpracticed']:
        accuracies = wit_df[(wit_df['Mapping'] == mapping) & (wit_df['Stage'] == stage)]['Mean Accuracy']
        res = scipy.stats.ttest_1samp(a=accuracies, popmean=0.25)
        lines.append((roi_name, stage, mapping, res.statistic, res.pvalue))

In [56]:
lines

[('yeo_network17_1',
  'Early',
  'Practiced',
  23.707392213567747,
  1.5614359179150618e-20),
 ('yeo_network17_1',
  'Early',
  'Unpracticed',
  23.23055377914691,
  2.73549916987868e-20),
 ('yeo_network17_1',
  'Late',
  'Practiced',
  19.61454073532123,
  2.7803492707320484e-18),
 ('yeo_network17_1',
  'Late',
  'Unpracticed',
  20.69879403933217,
  6.459536780466201e-19)]

In [57]:
lines = []

early_accuracies = [float(wit_df[(wit_df['Stage'] == 'Early') & (wit_df['Mapping'] == 'Practiced') & (wit_df['subj'] == subj)]['Mean Accuracy']) for subj in subj_list]
late_accuracies = [float(wit_df[(wit_df['Stage'] == 'Late') & (wit_df['Mapping'] == 'Practiced') & (wit_df['subj'] == subj)]['Mean Accuracy']) for subj in subj_list]
res = scipy.stats.ttest_rel(early_accuracies, late_accuracies)
print(res)

Ttest_relResult(statistic=-2.0911730804780535, pvalue=0.0453842147478905)

In [60]:
wit_df[(wit_df['Stage'] == 'Early') & (wit_df['Mapping'] == 'Practiced') & (wit_df['subj'] == subj)]['Mean Accuracy']

118    0.604167
Name: Mean Accuracy, dtype: float64

# DMN

In [63]:
df = pd.read_csv("/Volumes/clmnlab/GA/MVPA/LSS_pb02_MO_short_duration/roi_mvpa/20200313/dmn/20200317_dmn_module_dec-acc.csv")
df.tail()

     Unnamed: 0  subj roi_name      Mapping  Mean Accuracy  Stage
355         355  GA44    dMsub    Practiced       0.263889   Late
356         356  GA44   MTLsub  Unpracticed       0.489583  Early
357         357  GA44   MTLsub  Unpracticed       0.468750   Late
358         358  GA44   MTLsub    Practiced       0.361111  Early
359         359  GA44   MTLsub    Practiced       0.468750   Late

In [64]:
roi_names = sorted(set(df['roi_name']))

lines = []

for roi_name in roi_names:
    for stage in ['Early', 'Late']:
        for mapping in ['Practiced', 'Unpracticed']:
            accuracies = df[(df['Mapping'] == mapping) & (df['Stage'] == stage) & (df['roi_name'] == roi_name)]['Mean Accuracy']
            res = scipy.stats.ttest_1samp(a=accuracies, popmean=0.25)
            lines.append((roi_name, stage, mapping, res.statistic, res.pvalue))

In [66]:
result_df = pd.DataFrame(lines, columns=['cluster_name', 'stage', 'mapping', 't-value', 'p-value'])
result_df

   cluster_name  stage      mapping    t-value       p-value
0          Core  Early    Practiced   9.557470  1.824209e-10
1          Core  Early  Unpracticed   7.740036  1.553432e-08
2          Core   Late    Practiced   3.259191  2.851428e-03
3          Core   Late  Unpracticed   5.967202  1.742827e-06
4        MTLsub  Early    Practiced  12.597609  2.757169e-13
5        MTLsub  Early  Unpracticed  10.933011  8.399663e-12
6        MTLsub   Late    Practiced   7.334242  4.439901e-08
7        MTLsub   Late  Unpracticed   9.895958  8.362789e-11
8         dMsub  Early    Practiced   5.784743  2.879420e-06
9         dMsub  Early  Unpracticed   8.474080  2.449785e-09
10        dMsub   Late    Practiced   3.605832  1.152894e-03
11        dMsub   Late  Unpracticed   7.205886  6.214671e-08

In [68]:
result_df.to_csv('20200327_MVPA_dmn_1samp_statistics.csv')

In [71]:
lines = []

for roi_name in roi_names:
    early_accuracies = [float(df[(df['Stage'] == 'Early') & (df['Mapping'] == 'Practiced') & (df['roi_name'] == roi_name) & (df['subj'] == subj)]['Mean Accuracy']) for subj in subj_list]
    late_accuracies = [float(df[(df['Stage'] == 'Late') & (df['Mapping'] == 'Practiced') & (df['roi_name'] == roi_name) & (df['subj'] == subj)]['Mean Accuracy']) for subj in subj_list]
    res = scipy.stats.ttest_rel(early_accuracies, late_accuracies)
    lines.append((roi_name, res.statistic, res.pvalue, res.pvalue * 3))

In [72]:
lines

[('Core', 3.0472607854627793, 0.0048857555532197, 0.0146572666596591),
 ('MTLsub', 0.41247548036527953, 0.6830244440777922, 2.0490733322333767),
 ('dMsub', 2.139986180298939, 0.04089790421602002, 0.12269371264806006)]